### ISSUE TITLE
Not working in iPhone 6 running iOS 10.2 

### ISSUE THREAD

**Issue by poovamraj** [SethSky/KOPinCodeView#1]
Good work with the library. It works in iPhone 5s running 8.4 but not in the other version. No view is rendered there is just empty space.

**Comment by SethSky** [comment]
Hi. I did launch on iPhone 5 (10.3.3), iPhone 6s (11.2.0), iPhone 7 (11.2.1), and all working correctly. 
Maybe you will help example project and version 0.1.1.

**Comment by poovamraj** [comment]
No worries bro. I wrote a view on my own. Great library, guess the fault could be on my side.
